services:

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"   # jaeger ingest
      - "3200:3200"     # tempo
      - "9095:9095"     # tempo grpc
      - "4317:4317"     # otlp grpc
      - "4318:4318"     # otlp http
      - "9411:9411"     # zipkin
    networks:
      - tracing

  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
    networks:
      - tracing

  cpp-tempo:
    image: cpp-tempo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    ports:
      - "8080:8080"
    networks:
      - tracing

networks:
  tracing:
    driver: bridge

volumes:
  grafana_data:
  tempo_data: