name: Build and Deploy to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cpp, go, service-a, service-b]  # List of services to build and push
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker images for each service
      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}  # Each service has its own directory with Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ygiro-de-peppe-tempo/${{ matrix.service }}:latest

      # Optionally log out from Docker
      - name: Log out from GHCR
        run: docker logout
